IgnoreDirectoryMissingTrailingSlash: true
CheckDoctype: false
#CheckExternal: false
IgnoreDirs:
# This excludes are not optimal and need refinement. 
- "docs/0.\\d\\."
- "docs/0.10."
- "docs/0.11."
- "docs/0.12."
- "docs/0.13."
IgnoreURLs:
# GitHub Urls are ignored due to Request Limitations and getting a 429 instead
- "github.com/keptn/keptn/issues"
- "github.com/keptn/keptn/commit"
# Twitter seems to be not reachable via GitHub Action
- "twitter.com/keptnProject"
- "twitter.com/keptnproject"
# LinkedIn does not like automation and is returning a 999 Response Code
- "linkedin.com"
- "mailto"
- "localhost:8080"
- "YOUR-ORG"
- "YOUR.DOMAIN"
- "your.domain"
- "sockshop-dev"
- "nip.io"
StripQueryString: false
